### PR TITLE
Added support for ARM-Platforms

### PR DESCRIPTION
**Pull request by themorlan**
Hey,
as I wrote in one of my comments on the request for ARM-support I could not let the issue rest. So I dove into the topic and with the help of various guide managed to get is working (tested on amd64 VM and on my armhf-based NAS).
In summary I added two Dockerfiles, which run on the ARM-specific alpine images. To integrate these Dockerfiles into the autobuild function of Docker Hub I had to modify the hooks and also needed to add an emulator (qemu-user-static) into the docker. With these configurations the autobuild runs successfully (my test repo on docker hub: https://cloud.docker.com/u/morlan/repository/docker/morlan/calcardbackup).
Additionaly I created and pushed a docker manifest which contains the different images so that the user just has to pull the morlan/calcardbackup-latest image and receives the fitting image for his platform.
Cheers!

### CODE REVIEW

**Comment by themorlan** [comment]
Is there any problem with the PR? Or didn't you find the time to look at it, yet?

**Comment by waja** [comment]
Hi @themorlan,

> Is there any problem with the PR? Or didn't you find the time to look at it, yet?

I had a quick look into your PR, thanks for your work. What I'd like to prevent is to have different Dockerfiles per architecture (with mostly same content). This is too error prone in my eyes. Is the a chance to prevent this?

**Comment by themorlan** [comment]
Well most of the things I did is copy&paste from other sources. But I'll look into the buildx command mentioned in the article. Maybe there is a more compact way to set it all up.

**Comment by themorlan** [comment]
Buildx is not integrated yet into the autobuild function.

**Pull request closed without merging**
